AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template to create instance and output ID for
  transforming to an image.
Parameters:
    AwsRegion:
        Description: AWS region
        Type: String
        Default: "eu-west-1"
    NetworkStackName:
        Description: Network stack name that contains stack resources
        Type: String
    SecurityStackName:
        Description: Security stack name that contains stack resources
        Type: String
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: 'test'

Mappings:
  AWSRegionToAMI:
    eu-west-1:
      AMIID: ami-a1e6f5c7
    eu-central-1:
      AMIID: ami-9fea4ff0
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId:  !FindInMap [ AWSRegionToAMI , !Ref 'AWS::Region', AMIID ]
      SubnetId:
       Fn::ImportValue: !Join ['-', [!Sub "${NetworkStackName}", 'public', 'subnet', 'a', !Sub "${EnvironmentName}"]]
      SecurityGroupIds:
      - 'Fn::ImportValue': !Join ['-', [!Sub "${SecurityStackName}", 'sec', 'instance', !Sub "${EnvironmentName}"]]
      InstanceType: t2.micro
      KeyName: 'aws-shared'
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref 'AWS::StackName', 'instance', !Select [ 0, !GetAZs ], !Sub "${EnvironmentName}"]]
      - Key: Project
        Value: !Join ['', ['linux', 'academy', 'networking']]
Outputs:
  MachineIP:
    Description: IP Address of Machine
    Value: !GetAtt
      - Ec2Instance
      - PublicIp
