= *Useful Commands*

Full update
```bash
sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade -y
sudo apt-get upgrade linux-generic linux-headers-generic linux-image-generic
```

Clear
```bash
sudo apt-get autoclean && sudo apt-get autoremove -y && sudo apt-get clean
```
Clear cernet 
```bash
sudo apt-get purge $(dpkg -l linux-{image,headers}-"[0-9]*" | awk '/ii/{print $2}' | grep -ve "$(uname -r | sed -r 's/-[a-z]+//')")
```

Retrieve System Info
```bash
inxi -Fxz
lsb_release -a
sudo dmidecode | grep -A 9 "System Information"
```
Find files that matching names
```bash
find {directory} -name "{name|regex}"
sudo find / -type f -name "openvpn"
```

=== *Capabilties of the kernel*

```
grep Cap /proc/1/status
> CapInh:	00000000a80425fb
> CapPrm:	0000000000000000
> CapEff:	0000000000000000
> CapBnd:	00000000a80425fb
> CapAmb:	0000000000000000
```

```
nohup <command>
```

```
capsh --decode=00000000a80425fb
> 0x00000000a80425fb=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
```

=== *Displays files*

*  -a Displays hidden files or direcotry
*  -l Displays more information
* -h Display sizes in human readable format

*ls -alh*

Command allows file to be copied to, from, or between different host
```
scp <file> <ssh user and server>:<location where to>
```
Copy file from server
```bash
scp <ssh user and server>:<location where to> <location on local machine>
```

Output appended data from the file as the file grows
```bash
tail -f <file>
```

Selectively monitor the file
```bash
tail -f <file> | grep <what looking>
```

===Work with files
Move from directory to parent directory
```bash
mv . ..
```

*Untar*
```bash
tar -zxvf <file>.tgz -C <folder>
```
=== Profile updates

Without breaking current session, upgrade profile
```bash
source ~/.profile
```

Clean rubbish bin
```bash
rm -rf ~/.local/share/Trash/*
```

Get ip addresses
```bash
/sbin/ifconfig
```

Shows current mounted points and etc.
```bash
df -h
```

Constantly watches docker ps
```bash
watch -n <interval> docker ps
```

Swap files
```bash
cat /proc/meminfo to see total swap, and free swap (all linux)
cat /proc/swaps to see which swap devices are being used (all linux)
swapon -s to see swap devices and sizes (where swapon is installed)
```

System monitors
```bash
vmstat [-s] for current virtual memory statistics
free -m >> monitor memory usage.
top > used to monitor ram usage
htop > grafical interface.
```

Make 4g swap file
```bash
dd if=/dev/zero of=/tmp/.swapfile bs=10240 count=400000;
chmod 600 /tmp/.swapfile;
mkswap /tmp/.swapfile;
swapon /tmp/.swapfile;
```
```bash
~/.bashrc
alias update="sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade -y"
```

Downgrade Version
```
sudo apt install --reinstall package=version
```

Mate Specific
```
mate-control-center
```
