= *Useful Commands*

=== *Displays files*

*  -a Displays hidden files or direcotry
*  -l Displays more information
* -h Display sizes in human readable format

*ls -alh*

Command allows file to be copied to, from, or between different host
```
scp <file> <ssh user and server>:<location where to>
```
Copy file from server
```
scp <ssh user and server>:<location where to> <location on local machine>
```

Output appended data from the file as the file grows
```
tail -f <file>
```

Selectively monitor the file
```
tail -f <file> | grep <what looking>
```

===Work with files
Move from directory to parent directory
```
mv . ..
```

*Untar*
```
tar -zxvf <file>.tgz -C <folder>
```
=== Profile updates

Without breaking current session, upgrade profile
```
source ~/.profile
```

Clean rubbish bin
```
rm -rf ~/.local/share/Trash/*
```

Get ip addresses
```
/sbin/ifconfig
```
Shows current mounted points and etc.
```
df -h
```
Constantly watches docker ps
```
watch -n <interval> docker ps
````
Swap files
```
cat /proc/meminfo to see total swap, and free swap (all linux)
cat /proc/swaps to see which swap devices are being used (all linux)
swapon -s to see swap devices and sizes (where swapon is installed)

System monitors
```
vmstat [-s] for current virtual memory statistics
free -m >> monitor memory usage.
top > used to monitor ram usage
htop > grafical interface.
```
Make 4g swap file
```
dd if=/dev/zero of=/tmp/.swapfile bs=10240 count=400000;
chmod 600 /tmp/.swapfile;
mkswap /tmp/.swapfile;
swapon /tmp/.swapfile;
```
